Refactor/cases
conceptho/site pull request #37
Opened 2020-06-22 14:11 UTC by MayaraViana

Closes #33

2020-06-23 13:31 UTC, romulo1984 commented on src/components/ScrollHome.vue
> +        <div class="col-12 align-self-center">
Qualquer classe `col-x` só pode ser filha imediata de uma classe `row`, assim como a classe `row` só pode ter filhos imediatos das classes `col-x`.

2020-06-23 13:31 UTC, romulo1984 commented on src/components/ScrollHome.vue
> +  }
Aproveita pra indentar esse bloco.

2020-06-23 13:49 UTC, romulo1984 commented
@MayaraViana lembre de sempre começar um novo branch a partir de `refactor/new-design` e quando for abrir um PR apontar sempre pra ele também. Só faremos um PR pro master quando tudo tiver pronto pra ser lançado.

2020-07-02 21:51 UTC, MayaraViana commented
> @MayaraViana lembre de sempre começar um novo branch a partir de `refactor/new-design` e quando for abrir um PR apontar sempre pra ele também. Só faremos um PR pro master quando tudo tiver pronto pra ser lançado.

@romulo1984, isso aqui te falei que não entendi bem. Entendi até a parte de criar novo branch a partir, mas n entendi a parte do PR

2020-07-02 22:07 UTC, romulo1984 commented
@MayaraViana tranquilo, eu explico.

Como os branchs que estamos fazendo estão saindo de `refactor/new-design`, então quando temos algo pra ser revisado, ele tem que ter o PR apontando pra ele, já que tudo que está na branch master é o que está no site atualmente.

"Mas como assim, Rominho?"
- Me dê ibagens:

![Captura de Tela_Área de Seleção_20200702190116](https://user-images.githubusercontent.com/1641962/86413076-bc63e100-bc96-11ea-9e86-dc60f5383165.png)

Olha esse mesmo PR aqui que estamos comentando. Eu mesmo alterei ele pra apontar pro branch certo, que é o `refactor/new-design`. Na imagem, tá assim: "...`refactor/new-design` from `refactor/cases`. Ou seja, todas as mudanças que você fez, com o PR, você tá pedindo pra que o Github "mescle" com um outro branch. Ou seja, o do lado direito é o que vc fez e o do esquerdo é pra onde vc tá mandando, caso eu aprove o PR e dê merge.

E como faz isso?
Sempre quando você vai criar um PR, por padrão ele seleciona o branch de destino master. Então, ao criar, você terá sempre que mudar o branch de destino. Como vê na imagem abaixo, você escolhe no select da esquerda:
![Captura de Tela_Área de Seleção_20200702190151](https://user-images.githubusercontent.com/1641962/86413296-33997500-bc97-11ea-9aad-83e506a2de13.png)

Sacou?
Pode não ser simples agora o entendimento, mas podemos ver um dia pra dar uma geral dos conceitos básicos de como o Git faz as coisas.

2020-07-06 18:25 UTC, romulo1984 requested changes

2020-07-06 18:25 UTC, romulo1984 commented on src/components/ScrollHome.vue
> +          <div class="bg-image-club d-none d-md-block"></div>
Tá acontecendo novamente aqui, filhos imediatos de `row` que não são `col-x`.

Tente reorganizar as tags da página inteira para que siga as regras certinhas do bootstrap.
Vale dar uma lida aqui na documentação pra entender melhor: https://getbootstrap.com/docs/4.5/layout/grid/

2020-07-16 18:19 UTC, romulo1984 approved these changes

2020-07-16 18:19 UTC, merged